"""initial migration

Revision ID: 001_initial
Revises:
Create Date: 2026-07-31 17:37:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("nickname", sa.String(length=50), nullable=True),
        sa.Column("avatar", sa.String(length=255), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("credits", sa.Integer(), nullable=False),
        sa.Column("invite_code", sa.String(length=20), nullable=True),
        sa.Column("invited_by", sa.String(length=26), nullable=True),
        sa.Column("last_check_in_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_invite_code"), "users", ["invite_code"], unique=True)
    op.create_index(op.f("ix_users_phone"), "users", ["phone"], unique=True)

    op.create_table(
        "credit_logs",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("balance", sa.Integer(), nullable=False),
        sa.Column("related_id", sa.String(length=26), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_credit_logs_id"), "credit_logs", ["id"], unique=False)
    op.create_index(op.f("ix_credit_logs_related_id"), "credit_logs", ["related_id"], unique=False)
    op.create_index(op.f("ix_credit_logs_user_id"), "credit_logs", ["user_id"], unique=False)

    op.create_table(
        "invite_records",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("inviter_id", sa.String(length=26), nullable=False),
        sa.Column("invitee_id", sa.String(length=26), nullable=False),
        sa.Column("invitee_phone", sa.String(length=20), nullable=False),
        sa.Column("rewarded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["invitee_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["inviter_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invite_records_id"), "invite_records", ["id"], unique=False)
    op.create_index(op.f("ix_invite_records_invitee_id"), "invite_records", ["invitee_id"], unique=False)
    op.create_index(op.f("ix_invite_records_inviter_id"), "invite_records", ["inviter_id"], unique=False)

    op.create_table(
        "tasks",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("scenario_code", sa.String(length=50), nullable=False),
        sa.Column("scenario_name", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("conn_id", sa.String(length=64), nullable=True),
        sa.Column("task_id", sa.String(length=64), nullable=True),
        sa.Column("prompt_text", sa.Text(), nullable=True),
        sa.Column("chat_settings", sa.JSON(), nullable=True),
        sa.Column("current_event_id", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tasks_conn_id"), "tasks", ["conn_id"], unique=True)
    op.create_index(op.f("ix_tasks_id"), "tasks", ["id"], unique=False)
    op.create_index(op.f("ix_tasks_scenario_code"), "tasks", ["scenario_code"], unique=False)
    op.create_index(op.f("ix_tasks_status"), "tasks", ["status"], unique=False)
    op.create_index(op.f("ix_tasks_task_id"), "tasks", ["task_id"], unique=False)
    op.create_index(op.f("ix_tasks_user_id"), "tasks", ["user_id"], unique=False)

    op.create_table(
        "file_records",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("task_id", sa.String(length=26), nullable=True),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("file_type", sa.String(length=20), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("columns", sa.JSON(), nullable=True),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_file_records_id"), "file_records", ["id"], unique=False)
    op.create_index(op.f("ix_file_records_storage_key"), "file_records", ["storage_key"], unique=True)
    op.create_index(op.f("ix_file_records_task_id"), "file_records", ["task_id"], unique=False)
    op.create_index(op.f("ix_file_records_user_id"), "file_records", ["user_id"], unique=False)

    op.create_table(
        "reports",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("task_id", sa.String(length=26), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("overall_score", sa.String(length=10), nullable=True),
        sa.Column("health_scores", sa.JSON(), nullable=True),
        sa.Column("kpis", sa.JSON(), nullable=True),
        sa.Column("charts", sa.JSON(), nullable=True),
        sa.Column("conclusions", sa.JSON(), nullable=True),
        sa.Column("actions", sa.JSON(), nullable=True),
        sa.Column("raw_data_summary", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("markdown_content", sa.Text(), nullable=True),
        sa.Column("pdf_url", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reports_id"), "reports", ["id"], unique=False)
    op.create_index(op.f("ix_reports_task_id"), "reports", ["task_id"], unique=True)
    op.create_index(op.f("ix_reports_user_id"), "reports", ["user_id"], unique=False)

    op.create_table(
        "share_snapshots",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("share_type", sa.String(length=20), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("report_id", sa.String(length=26), nullable=True),
        sa.Column("task_id", sa.String(length=26), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("snapshot_data", sa.JSON(), nullable=False),
        sa.Column("poster_url", sa.String(length=500), nullable=True),
        sa.Column("password", sa.String(length=64), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("view_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["report_id"], ["reports.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_share_snapshots_id"), "share_snapshots", ["id"], unique=False)
    op.create_index(op.f("ix_share_snapshots_report_id"), "share_snapshots", ["report_id"], unique=False)
    op.create_index(op.f("ix_share_snapshots_task_id"), "share_snapshots", ["task_id"], unique=False)
    op.create_index(op.f("ix_share_snapshots_token"), "share_snapshots", ["token"], unique=True)
    op.create_index(op.f("ix_share_snapshots_user_id"), "share_snapshots", ["user_id"], unique=False)

    op.create_table(
        "policy_feeds",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("source", sa.String(length=200), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("region", sa.String(length=100), nullable=True),
        sa.Column("industry", sa.String(length=100), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("publish_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("view_count", sa.Integer(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_policy_feeds_id"), "policy_feeds", ["id"], unique=False)
    op.create_index(op.f("ix_policy_feeds_industry"), "policy_feeds", ["industry"], unique=False)
    op.create_index(op.f("ix_policy_feeds_region"), "policy_feeds", ["region"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("policy_feeds")
    op.drop_table("share_snapshots")
    op.drop_table("reports")
    op.drop_table("file_records")
    op.drop_table("tasks")
    op.drop_table("invite_records")
    op.drop_table("credit_logs")
    op.drop_table("users")
    # ### end Alembic commands ###
